### ISSUE TITLE
Can't Access Google Forms

### ISSUE THREAD

**Issue by suvilocke** [Video-Game-Development-Club/first-game#4]
I understand it's a tad early, but I'm excited to start this project, and I can't access the Google Forms page - something about a separate organization. Can this be fixed, or is it just like that until Tuesday, when we meet officially?

**Comment by Bubadabado** [comment]
I was hoping that wouldn't happen. I might need to manually invite everyone to the Google form.  It doesn't have a timer or anything like that, so I will see if I can fix it.

**Comment by Bubadabado** [comment]
okay, I believe it is fixed but if not let me know.

**Comment by suvilocke** [comment]
Not quite. I still get an error message.

"This form can only be viewed by users in the owner's organization. Try contacting the owner of the form if you think this is a mistake."

Then again, I'm not signed in to the account I signed up with, so that may have been the issue. I'll be sure to look into it later.

**Comment by Bubadabado** [comment]
I re sent it again and it works now.
